### ISSUE TITLE
@Reference引用的服务，在调用过程中为空

### ISSUE THREAD

**Issue by yoyokeen** [dangdangdotcom/dubbox#103]
![Uploading image.png…]()

java.lang.NullPointerException
	at com.yoyo.service.BookService.Insert(BookService.java:24)
	at com.yoyo.controller.BookController.booklist(BookController.java:33)

**Comment by yoyokeen** [comment]
@Reference(version="1.0.0")
    private JpaService jpaService;

    public int Insert()
    {
       return jpaService.InsertData();

**Comment by yoyokeen** [comment]
请问，这个问题是怎么产生的？服务没有初始化

**Comment by dimmacro** [comment]
有可能服务提供方没有注册
