### ISSUE TITLE
部署在Tomcat中的dubbox，关闭时DubboShutdownHook执行失败

### ISSUE THREAD

**Issue by Np0C** [dangdangdotcom/dubbox#116]
Tomcat关闭之后，Hook执行时Load不到class
堆栈如下。
=====
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [com.alibaba.dubbo.registry.support.SkipFailbackWrapperException]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1315)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1178)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1139)

**Comment by eoc2015** [comment]
我也是……没办法我kill 9了
后来怎么解决的？
