### ISSUE TITLE
在REST方式下，添加ContainerResponseFilter后，客户端调用报ClassNotFound

### ISSUE THREAD

**Issue by keepitalive** [dangdangdotcom/dubbox#128]
Hi,

我正在尝试使用rest方式暴露服务，感谢你们，这个非常容易就实现了。后来我希望这个api能直接在swagger ui上调用，所以另外增加一个ContainerResponseFilter以支持CORS，通过在provider端加了这个extension实现。然而在consumer端通过dubbo client调用的时候也会尝试去load这个filter，然后会报class not found（我认为这个是服务端的filter，客户端理论上是不会需要这个class的，所以没有把这个filter放到api jar中）。我感觉是不是因为这个extension出现在服务的URL上，以至于consumer端也认为需要用到这个extension而尝试去load它呢？还是说我在某些地方缺少了配置？

期待你们的回复，THX

Eric

Exception：
com.alibaba.dubbo.rpc.RpcException: Error loading JAX-RS extension class: com.bravo.member.app.gateway.ApiOriginFilter
	at com.alibaba.dubbo.rpc.protocol.rest.RestProtocol.doRefer(RestProtocol.java:180)
	at com.alibaba.dubbo.rpc.protocol.AbstractProxyProtocol.refer(AbstractProxyProtocol.java:88)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:65)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:62)
	at com.alibaba.dubbo.rpc.Protocol$Adpative.refer(Protocol$Adpative.java)
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.toInvokers(RegistryDirectory.java:395)
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:224)
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:195)
	at com.alibaba.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:449)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:273)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:259)
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:170)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:189)
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:133)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:271)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:254)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:63)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:60)
	at com.alibaba.dubbo.rpc.Protocol$Adpative.refer(Protocol$Adpative.java)
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:392)
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:300)
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:138)
	at com.alibaba.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:65)

**Comment by li-shen** [comment]
Extension必须在服务端和客户端都存在
