### ISSUE TITLE
代码无法运行com.alibaba.dubbo.container.Main

### ISSUE THREAD

**Issue by shikaiwen** [dangdangdotcom/dubbox#153]
刚下载的代码运行com.alibaba.dubbo.container.Main，直接报错了
···
java.lang.IllegalStateException: No such extension com.alibaba.dubbo.container.Container by name spring at com.alibaba.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:494)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:501)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:319)
	at com.alibaba.dubbo.container.Main.main(Main.java:56)

···

**Comment by StonyShi** [comment]
在dubbo.perproties 配置下 container

**Comment by caokang** [comment]
我是切换Tags到dubbox-2.8.4下，可以运行起来。。

**Comment by yilan13** [comment]
我也遇到这个问题了。。刚拉的最新master，没改动，报这个错。。

**Comment by bearDream** [comment]
不知道为什么就是无法加载com.alibaba.dubbo.container.spring模块下resources的com.alibaba.dubbo.container.Container,蛋疼
