### ISSUE TITLE
2.8.4版本，消费端和服务端都使用Rest协议，异常在消费端无法显示原信息

### ISSUE THREAD

**Issue by AI-PaaS** [dangdangdotcom/dubbox#156]
在消费端，异常仅显示：Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:189)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:154)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:58)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:62)

**Comment by nbqyqx** [comment]
需要自己增加异常处理过滤器来封装（服务端）和处理（客户端）异常，然后在客户端重新抛出。我们把服务端异常封装到自定义的Result对象里，在客户端用切面解开重新抛出。
