### ISSUE TITLE
通过dubbox框架使用thrift async方式出现空指针

### ISSUE THREAD

**Issue by 8241796** [dangdangdotcom/dubbox#213]
同样的代码，实现了$Iface的同步接口，客户端调用没问题，但是实现了$Asyncface，远端一调用就报下面的错误：

com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method getUserInfo in the service com.yuntongxun.udas.service.OamUserDataService$AsyncIface. Tried 3 times of the providers [192.168.178.160:30001] (1/1) from the registry 123.57.140.180:2181 on the consumer 192.168.178.160 using the dubbo version 2.8.4. Last error is: Failed to send message Request [id=5, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=getUserInfo, parameterTypes=[class java.lang.String, interface org.apache.thrift.async.AsyncMethodCallback], arguments=[liwenchao, com.yuntongxun.yoyaclient.service.impl.DemoAction$MyCallback@68569dd5], attachments={class.name.generator=dubbo, path=com.yuntongxun.udas.service.OamUserDataService$AsyncIface, interface=com.yuntongxun.udas.service.OamUserDataService$AsyncIface, async=false}]] to /192.168.178.160:30001, cause: null
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:101)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
	at com.alibaba.dubbo.common.bytecode.proxy0.getUserInfo(proxy0.java)
	at com.yuntongxun.yoyaclient.service.impl.DemoAction.start(DemoAction.java:92)
	at com.yuntongxun.yoyaclient.YoYaClient.main(YoYaClient.java:61)
Caused by: com.alibaba.dubbo.remoting.RemotingException: Failed to send message Request [id=5, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=getUserInfo, parameterTypes=[class java.lang.String, interface org.apache.thrift.async.AsyncMethodCallback], arguments=[liwenchao, com.yuntongxun.yoyaclient.service.impl.DemoAction$MyCallback@68569dd5], attachments={class.name.generator=dubbo, path=com.yuntongxun.udas.service.OamUserDataService$AsyncIface, interface=com.yuntongxun.udas.service.OamUserDataService$AsyncIface, async=false}]] to /192.168.178.160:30001, cause: null
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:108)
	at com.alibaba.dubbo.remoting.transport.AbstractClient.send(AbstractClient.java:270)
	at com.alibaba.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:51)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.request(HeaderExchangeChannel.java:112)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeClient.request(HeaderExchangeClient.java:91)
	at com.alibaba.dubbo.rpc.protocol.thrift.ThriftInvoker.doInvoke(ThriftInvoker.java:88)
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:146)
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
	... 6 more
Caused by: java.lang.NullPointerException
	at com.alibaba.dubbo.rpc.protocol.thrift.ThriftCodec.encodeRequest(ThriftCodec.java:460)
	at com.alibaba.dubbo.rpc.protocol.thrift.ThriftCodec.encode(ThriftCodec.java:102)
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalEncoder.encode(NettyCodecAdapter.java:81)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:66)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
	at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.writeRequested(NettyHandler.java:99)
	at org.jboss.netty.channel.Channels.write(Channels.java:704)
	at org.jboss.netty.channel.Channels.write(Channels.java:671)
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248)
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:98)
	... 21 more

有没有人遇见过呢？

**Comment by zhangyq1011** [comment]
> 同样的代码，实现了$Iface的同步接口，客户端调用没问题，但是实现了$Asyncface
没用使用过thrift

**Comment by 8241796** [comment]
报错的位置如下：

  for( int i = 0; i < inv.getArguments().length; i++ ) {

            Object obj = inv.getArguments()[i];

            if ( obj == null ) { continue; }

            TFieldIdEnum field = args.fieldForId( i + 1 );

            String setMethodName = ThriftUtils.generateSetMethodName( field.getFieldName() );

            Method method;

            try {
                method = clazz.getMethod( setMethodName, inv.getParameterTypes()[i] );
            } catch ( NoSuchMethodException e ) {
                throw new RpcException( RpcException.SERIALIZATION_EXCEPTION, e.getMessage(), e );
            }

            try {
                method.invoke( args, obj );
            } catch ( IllegalAccessException e ) {
                throw new RpcException( RpcException.SERIALIZATION_EXCEPTION, e.getMessage(), e );
            } catch ( InvocationTargetException e ) {
                throw new RpcException( RpcException.SERIALIZATION_EXCEPTION, e.getMessage(), e );
            }

        }


报错的代码为： String setMethodName = ThriftUtils.generateSetMethodName( field.getFieldName() );

field 为null

**Comment by 8241796** [comment]
void getUserInfo(String userName, AsyncMethodCallback resultHandler) throws TException;

只是多了一个AsyncMethodCallback参数。
