### ISSUE TITLE
2.8.4的源代码你们是怎么编译通过的？

### ISSUE THREAD

**Issue by fengyunhe** [dangdangdotcom/dubbox#315]
我这里一直出现警告：
[WARNING] The POM for com.alibaba:dubbo-config-api:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-config-spring/2.8.4/dubbo-config-spring-2.8.4.pom
             [WARNING] The POM for com.alibaba:dubbo-config-spring:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-remoting-netty/2.8.4/dubbo-remoting-netty-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-remoting-netty:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-remoting-mina/2.8.4/dubbo-remoting-mina-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-remoting-mina:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-remoting-grizzly/2.8.4/dubbo-remoting-grizzly-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-remoting-grizzly:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-remoting-p2p/2.8.4/dubbo-remoting-p2p-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-remoting-p2p:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-remoting-http/2.8.4/dubbo-remoting-http-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-remoting-http:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-rpc-default/2.8.4/dubbo-rpc-default-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-rpc-default:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-rpc-injvm/2.8.4/dubbo-rpc-injvm-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-rpc-injvm:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-rpc-rmi/2.8.4/dubbo-rpc-rmi-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-rpc-rmi:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-rpc-hessian/2.8.4/dubbo-rpc-hessian-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-rpc-hessian:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-rpc-http/2.8.4/dubbo-rpc-http-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-rpc-http:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-rpc-webservice/2.8.4/dubbo-rpc-webservice-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-rpc-webservice:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-rpc-thrift/2.8.4/dubbo-rpc-thrift-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-rpc-thrift:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-rpc-memcached/2.8.4/dubbo-rpc-memcached-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-rpc-memcached:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-rpc-redis/2.8.4/dubbo-rpc-redis-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-rpc-redis:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-rpc-rest/2.8.4/dubbo-rpc-rest-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-rpc-rest:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-registry-default/2.8.4/dubbo-registry-default-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-registry-default:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-registry-multicast/2.8.4/dubbo-registry-multicast-2.8.4.pom
[WARNING] The POM for com.alibaba:dubbo-registry-multicast:jar:2.8.4 is missing, no dependency information available
Downloading: http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/dubbo-registry-zookeeper/2.8.4/dubbo-registry-zookeeper-2.8.4.pom

**Comment by FangOba** [comment]
在根目录下执行mvn clean install -Dmaven.test.skip=true就可以了呀，不知道你具体怎么弄的哦，可以再详细些吗

**Comment by MarsYoung** [comment]
进parent编译啊、、

**Comment by SkyBridge007** [comment]
# dubbox-2.8.4 的本地编译确实不容易成功，我是修改了两个文件才成功。
本地环境信息：
```
OS:win7
Java: "1.7.0_75"
Maven:3.3.9
Eclipse:Mars.2 Release (4.5.2)
```
## 1.修改dubbox/pom.xml中jetty和cxf的版本，原本是
```
<jetty_version>6.1.26</jetty_version>
<cxf_version>2.6.1</cxf_version>
```
修改为
```
<jetty_version>6.1.25</jetty_version>
<cxf_version>2.6.16</cxf_version>
```
## 2.修改dubbo-rpc-thrift/pom.xml，添加commons-lang包的依赖
            <dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
			<version>2.6</version>
		</dependency>
### 如果不修改这些，我本地在编译的时候会抛下面几个错误，不知道别人会不会是这样。
第一个错误
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.536 s
[INFO] Finished at: 2017-06-10T10:28:22+08:00
[INFO] Final Memory: 27M/218M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project
 dubbo-container-jetty: Compilation failure: Compilation failure:
[ERROR] \Users\Administrator\git\dubbox\dubbo-container\dubbo-container-jetty\src\main\java\com\alibaba\dubbo\container\
jetty\JettyContainer.java:[61,17] 错误: 无法访问AbstractLifeCycle
[ERROR] \Users\Administrator\git\dubbox\dubbo-container\dubbo-container-jetty\src\main\java\com\alibaba\dubbo\container\
jetty\JettyContainer.java:[78,18] 错误: 找不到符号
[ERROR] \Users\Administrator\git\dubbox\dubbo-container\dubbo-container-jetty\src\main\java\com\alibaba\dubbo\container\
jetty\JettyContainer.java:[86,26] 错误: 二元运算符 '!=' 的操作数类型错误
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dubbo-container-jetty
```
第二错误
```
[INFO] Building dubbo-rpc-webservice 2.8.4
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.apache.cxf:cxf-rt-frontend-simple:jar:2.6.1 is invalid, transitive dependencies (if any) will
not be available, enable debug logging for more details
[WARNING] The POM for org.apache.cxf:cxf-rt-transports-http:jar:2.6.1 is invalid, transitive dependencies (if any) will
not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ dubbo-rpc-webservice ---
[INFO] Deleting E:\Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ dubbo-rpc-webservice ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ dubbo-rpc-webservice ---
[INFO] Compiling 1 source file to E:\Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[28,35] 错误: 程序包org.apache.cxf.bus.extension不存在
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[29,30] 错误: 程序包org.apache.cxf.endpoint不存在
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[33,33] 错误: 程序包org.apache.cxf.interceptor不存在
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[62,18] 错误: 找不到符号
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[62,48] 错误: 找不到符号
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[64,58] 错误: 无法访问Bus
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[69,14] 错误: 找不到符号
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[94,73] 错误: 无法访问AbstractTransportFactory
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[112,25] 错误: 无法访问AbstractEndpointFactory
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[116,25] 错误: 找不到符号
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[117,29] 错误: 无法访问Server
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[128,21] 错误: 无法访问AbstractBasicInterceptorProvider
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[132,5] 错误: 找不到符号
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[132,41] 错误: 无法访问Client
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[135,8] 错误: 无法访问TExtensibilityElementImpl
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[137,9] 错误: 无法访问AbstractConduit
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[142,22] 错误: 找不到符号
[INFO] 17 errors
[INFO] -------------------------------------------------------------
```
第三个错误：
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:11 min
[INFO] Finished at: 2017-06-09T22:36:36+08:00
[INFO] Final Memory: 23M/219M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project
 dubbo-rpc-webservice: Compilation failure: Compilation failure:
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[28,35] 错误: 程序包org.apache.cxf.bus.extension不存在
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[29,30] 错误: 程序包org.apache.cxf.endpoint不存在
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[33,33] 错误: 程序包org.apache.cxf.interceptor不存在
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[62,18] 错误: 找不到符号
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[62,48] 错误: 找不到符号
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[64,58] 错误: 无法访问Bus
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[69,14] 错误: 找不到符号
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[94,73] 错误: 无法访问AbstractTransportFactory
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[112,25] 错误: 无法访问AbstractEndpointFactory
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[116,25] 错误: 找不到符号
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[117,29] 错误: 无法访问Server
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[128,21] 错误: 无法访问AbstractBasicInterceptorProvider
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[132,5] 错误: 找不到符号
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[132,41] 错误: 无法访问Client
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[135,8] 错误: 无法访问TExtensibilityElementImpl
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[137,9] 错误: 无法访问AbstractConduit
[ERROR] \Users\Administrator\git\dubbox\dubbo-rpc\dubbo-rpc-webservice\src\main\java\com\alibaba\dubbo\rpc\protocol\webs
ervice\WebServiceProtocol.java:[142,22] 错误: 找不到符号
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dubbo-rpc-webservice
```
### 补充一个信息，打包完成后使用dubbo-monitor-simple时启动报错：
```
D:\repository\com\alibaba\dubbo-monitor-simple\2.8.4\dubbo-monitor-simple-2.8.4\bin>start.bat
log4j:WARN No appenders could be found for logger (com.alibaba.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'monitorService' defined in URL [
jar:file:/D:/repository/com/alibaba/dubbo-monitor-simple/2.8.4/dubbo-monitor-simple-2.8.4/lib/dubbo-monitor-simple-2.8.4
.jar!/META-INF/spring/dubbo-monitor-simple.xml]: Instantiation of bean failed; nested exception is java.lang.NoClassDefF
oundError: org/jfree/date/MonthConstants
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowire
CapableBeanFactory.java:1037)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutow
ireCapableBeanFactory.java:983)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCap
ableBeanFactory.java:487)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapab
leBeanFactory.java:458)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegis
try.java:223)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListable
BeanFactory.java:633)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplic
ationContext.java:932)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java
:139)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java
:93)
        at com.alibaba.dubbo.container.spring.SpringContainer.start(SpringContainer.java:50)
        at com.alibaba.dubbo.container.Main.main(Main.java:80)
Caused by: java.lang.NoClassDefFoundError: org/jfree/date/MonthConstants
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2585)
        at java.lang.Class.getConstructor0(Class.java:2885)
        at java.lang.Class.getDeclaredConstructor(Class.java:2058)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy
.java:78)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowire
CapableBeanFactory.java:1030)
        ... 14 more
Caused by: java.lang.ClassNotFoundException: org.jfree.date.MonthConstants
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 32 more
请按任意键继续. . .
```
### 于是我在dubbo-monitor-simple/pom.xml文件中加入 
```
		<dependency>
    		    <groupId>jfree</groupId>
    		    <artifactId>jcommon</artifactId>
    		    <version>1.0.13</version>
		</dependency>
```
