### ISSUE TITLE
dubbox在tomcat容器中使用，shutdown关闭的时候JVM无法结束

### ISSUE THREAD

**Issue by deepshrift** [dangdangdotcom/dubbox#58]
dubbox 8月份拉取的最新版本。JDK7下构建。
运行环境是  tomcat8+JDK8
程序使用JDK8开发，编译级别JDK7
问题对我们困扰非常大，还请高手们帮忙分析下，多谢啦！

在执行tomcat的shutdown后，日志中出现很多memoryleak的错误，JVM无法结束。 按照https://github.com/alibaba/dubbo/issues/95 的建议，加入了ApplicationListener<ContextClosedEvent>执行ProtocolConfig.destroyAll()。 dubbo服务提供者端的tomcat可以正常关闭，但是dubbo 消费者端tomcat关闭后jvm进程仍然在。
经过观察，凡是JVM进程不能结束，tomcat日志有如下错误：
22-Oct-2015 19:38:39.178 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [wx-business] created a ThreadLocal with key of type [com.alibaba.dubbo.rpc.RpcContext$1] (value [com.alibaba.dubbo.rpc.RpcContext$1@3fcbc3da]) and a value of type [com.alibaba.dubbo.rpc.RpcContext] (value [com.alibaba.dubbo.rpc.RpcContext@1f4bdee]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
22-Oct-2015 19:38:39.196 INFO [localhost-startStop-1-SendThread(10.135.100.231:2181)] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.apache.zookeeper.server.ZooTrace]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.zookeeper.server.ZooTrace]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1335)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1321)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1203)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1164)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1128)

22-Oct-2015 19:38:39.200 INFO [localhost-startStop-1-SendThread(10.135.100.231:2181)] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1335)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1321)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1203)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1164)
        at org.apache.logging.log4j.core.impl.Log4jLogEvent.getThrownProxy(Log4jLogEvent.java:323)
        at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:64)
        at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:36)
        at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:196)
        at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:55)
        at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:71)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:108)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:412)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
        at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
        at org.apache.logging.slf4j.Log4jLogger.error(Log4jLogger.java:318)
        at org.apache.zookeeper.ClientCnxn$1.uncaughtException(ClientCnxn.java:414)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:1952)

22-Oct-2015 19:38:39.206 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-18080"]
2015-10-22 19:38:39,202 ERROR An exception occurred processing Appender Console java.lang.IllegalStateException: Can't overwrite cause with java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.logging.log4j.core.impl.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at java.lang.Throwable.initCause(Throwable.java:457)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1324)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1203)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1164)
        at org.apache.logging.log4j.core.impl.Log4jLogEvent.getThrownProxy(Log4jLogEvent.java:323)
        at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:64)
        at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:36)
        at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:196)
        at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:55)
        at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:71)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:108)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:412)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
        at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
        at org.apache.logging.slf4j.Log4jLogger.error(Log4jLogger.java:318)
        at org.apache.zookeeper.ClientCnxn$1.uncaughtException(ClientCnxn.java:414)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:1952)
Caused by: java.lang.ClassNotFoundException
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1323)
        ... 20 more

**Comment by li-shen** [comment]
关不掉可以试试用最新snapshot。如果是强行关机，threadlocal没有释放也没什么，正常调用应该有释放程序

**Comment by li-shen** [comment]
关不掉可以试试用最新snapshot。如果是强行关机，threadlocal没有释放也没什么，正常调用应该有释放程序

**Comment by mauersu** [comment]
kill -9 大家都这么追求完美吗？

**Comment by XiaochunLU** [comment]
工作流程上要求自动部署，现在引入dubbo后，tomcat重新部署某个应用就hang在那边了，流程走不下去

**Comment by ulfsar** [comment]
@XiaochunLU 
直接release,channelFactory.如果有正在进行的任务,会有怎样的结果?

**Comment by tanbw** [comment]
我们在linux服务器上做并发测试时也发现了这个问题，总是有n个消费端和服务端的进程无法关闭，导致下次启动失败
我们在配置了客户端init=true（启动容器时初始化消费端）以后没这个问题了，你们也可以试试

**Comment by cuiyang-org** [comment]
我也遇到了你这个问题。我跟踪了下，消费端一直没有在ZooKeeper注册中心注销。你看下你的ZooKeeper版本是不是3.3.3。你把ZooKeeper版本换成3.4.5试一试。zkclient0.1间接依赖的ZooKeeper版本是3.3.3。

**Comment by StonyShi** [comment]
public class WebContextListener implements ApplicationListener {
    private static final Logger logger = LoggerFactory.getLogger(WebContextListener.class);

    @Override
    public void onApplicationEvent(ApplicationEvent applicationEvent) {
        if (applicationEvent instanceof ContextStartedEvent){
            logger.debug("It was Started.");
        }

        if (applicationEvent instanceof ContextClosedEvent){
            ContextClosedEvent event = (ContextClosedEvent) applicationEvent;
            if(event.getApplicationContext().getParent()==null){
                logger.debug("App context was Closed.");
                synchronized (Main.class) {
                    try {
                        Main.class.notifyAll();
                    } catch (Throwable e) {}
                }
                Runtime.getRuntime().exit(0);
            }else{
                logger.debug("Web context was Closed.");
            }
            event = null;
        }
    }
}

**Comment by StonyShi** [comment]
用一个监听ContextClosed 方法来关闭

**Comment by Np0C** [comment]
我也遇到这个问题了，查了jstack发现除了主线程之外还有一个非deamon线程。
````
"Hashed wheel timer #1@4029" prio=5 tid=0x32 nid=NA sleeping
  java.lang.Thread.State: TIMED_WAITING
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at org.jboss.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:503)
	  at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:401)
	  at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	  at java.lang.Thread.run(Thread.java:745)
````

**Comment by Np0C** [comment]
刚才发现这个Hashed wheel timer使用的是Executors.DefaultThreadFactory.newThread创建的，所以是non-daemon。所以导致了tomcat主进程无法终止。#117
