### ISSUE TITLE
javassist 在jdk8下面 有些服务发布失败

### ISSUE THREAD

**Issue by zhaiyuyong** [dangdangdotcom/dubbox#85]
Caused by: java.lang.RuntimeException: java.io.IOException: invalid constant type: 18
 at javassist.CtClassType.getClassFile2(CtClassType.java:203)
 at javassist.CtClassType.subtypeOf(CtClassType.java:303)
 at javassist.CtClassType.subtypeOf(CtClassType.java:318)
 at javassist.compiler.MemberResolver.compareSignature(MemberResolver.java:247)
 at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:119)
 at javassist.compiler.MemberResolver.lookupMethod(MemberResolver.java:96)
 at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:704)
 at javassist.expr.NewExpr$ProceedForNew.setReturnType(NewExpr.java:243)
 at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:146)
 at javassist.compiler.ast.CallExpr.accept(CallExpr.java:45)
 at javassist.compiler.TypeChecker.atVariableAssign(TypeChecker.java:248)
 at javassist.compiler.TypeChecker.atAssignExpr(TypeChecker.java:217)
 at javassist.compiler.ast.AssignExpr.accept(AssignExpr.java:38)

升级javassist 到3.18或以上版本
见[http://jasonli.info/archives/506.html](url)

**Comment by coder-han** [comment]
thank,完美解决.有分析出是什么原因吗?

**Comment by zhaiyuyong** [comment]
不兼容吧？具体什么原因没找到

**Comment by coder-han** [comment]
应该是不兼容,我也没细看,就解决了..
