### ISSUE TITLE
dubbox 2.8.4 用spring 4.2.1.RELEASE连接不上zk(zookeeper-3.4.6.tar)报错如下：

### ISSUE THREAD

**Issue by mtdp** [dangdangdotcom/dubbox#90]
6-02-25 13:24:48 DEBUG main-EventThread - Received event: WatchedEvent state:SyncConnected type:None path:null
2016-02-25 13:24:48 DEBUG main-SendThread(ALDBIT1:2182) - Reading reply sessionid:0x252f8b239610023, packet:: clientPath:null serverPath:null finished:false header:: 1,-11  replyHeader:: 1,4294969409,0  request:: null response:: null
2016-02-25 13:24:48 DEBUG main-SendThread(ALDBIT1:2182) - An exception was thrown while closing send thread for session 0x252f8b239610023 : Unable to read additional data from server sessionid 0x252f8b239610023, likely server has closed socket
2016-02-25 13:24:48 DEBUG main - Disconnecting client for session: 0x252f8b239610023
2016-02-25 13:24:48 INFO main - Session: 0x252f8b239610023 closed
2016-02-25 13:24:48 DEBUG main - Closing ZkClient...done
2016-02-25 13:24:48 ERROR main - Context initialization failed
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 5000
    at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1183) ~[zkclient-0.6.jar:0.6]
    at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:147) ~[zkclient-0.6.jar:0.6]
    at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:122) ~[zkclient-0.6.jar:0.6]
    at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:118) ~[zkclient-0.6.jar:0.6]
    at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:85) ~[zkclient-0.6.jar:0.6]

**Comment by 0xffff00** [comment]
遇到同样错误

**Comment by mtdp** [comment]
我的原因是dev环境网络问题，超时时间修改成6000，问题解决了
